### ISSUE TITLE
lightsale은 유료인가요?

### ISSUE THREAD

**Issue by mwy3055** [kyaryunha/kyaryunha.com-new#1]
* 갑자기 궁금해졌어요

**Comment by kyaryunha** [comment]
네 유료입니다 ! 

AWS 의 EC2 는 빌링에서 얼마 나오는지 체크하기 전에, 사전에 미리 알 수 없는데, 
Lightsail은 사전에 월별 요금을 미리 알려주기에 학생때 원하는 요금 수준을 생각하며 쓰기에 편리한 것 같아요. 


> Lightsail 의 요금제 창 

<img width="906" alt="스크린샷 2020-12-01 오전 12 40 34" src="https://user-images.githubusercontent.com/37409087/100630380-d43ab080-336d-11eb-98d3-0035cdf3dca3.png">

**Comment by mwy3055** [comment]
오 정액제구나.. 좋은 정보 감사합니다
